# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: <%= ENV["redis://redistogo:a1ece38c834a29a351be322467802ff9@soldierfish.redistogo.com:11807/"] %>

development:
  adapter: async

test:
  adapter: async
